# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

import image_recon_pb2 as image__recon__pb2


class RecognizerStub(object):
  # missing associated documentation comment in .proto file
  pass

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.flowers = channel.unary_unary(
        '/Recognizer/flowers',
        request_serializer=image__recon__pb2.Input.SerializeToString,
        response_deserializer=image__recon__pb2.Output.FromString,
        )
    self.dogs = channel.unary_unary(
        '/Recognizer/dogs',
        request_serializer=image__recon__pb2.Input.SerializeToString,
        response_deserializer=image__recon__pb2.Output.FromString,
        )


class RecognizerServicer(object):
  # missing associated documentation comment in .proto file
  pass

  def flowers(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def dogs(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_RecognizerServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'flowers': grpc.unary_unary_rpc_method_handler(
          servicer.flowers,
          request_deserializer=image__recon__pb2.Input.FromString,
          response_serializer=image__recon__pb2.Output.SerializeToString,
      ),
      'dogs': grpc.unary_unary_rpc_method_handler(
          servicer.dogs,
          request_deserializer=image__recon__pb2.Input.FromString,
          response_serializer=image__recon__pb2.Output.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'Recognizer', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
