# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: image_recon.proto

from google.protobuf import symbol_database as _symbol_database
from google.protobuf import reflection as _reflection
from google.protobuf import message as _message
from google.protobuf import descriptor as _descriptor
import sys
_b = sys.version_info[0] < 3 and (
    lambda x: x) or (lambda x: x.encode('latin1'))
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


DESCRIPTOR = _descriptor.FileDescriptor(
    name='image_recon.proto',
    package='',
    syntax='proto3',
    serialized_options=None,
    serialized_pb=_b('\n\x11image_recon.proto\"(\n\x05Input\x12\r\n\x05model\x18\x01 \x01(\t\x12\x10\n\x08img_path\x18\x02 \x01(\t\"+\n\x06Output\x12\x12\n\ndelta_time\x18\x01 \x01(\t\x12\r\n\x05top_5\x18\x02 \x01(\t2E\n\nRecognizer\x12\x1c\n\x07\x66lowers\x12\x06.Input\x1a\x07.Output\"\x00\x12\x19\n\x04\x64ogs\x12\x06.Input\x1a\x07.Output\"\x00\x62\x06proto3')
)


_INPUT = _descriptor.Descriptor(
    name='Input',
    full_name='Input',
    filename=None,
    file=DESCRIPTOR,
    containing_type=None,
    fields=[
        _descriptor.FieldDescriptor(
            name='model', full_name='Input.model', index=0,
            number=1, type=9, cpp_type=9, label=1,
            has_default_value=False, default_value=_b("").decode('utf-8'),
            message_type=None, enum_type=None, containing_type=None,
            is_extension=False, extension_scope=None,
            serialized_options=None, file=DESCRIPTOR),
        _descriptor.FieldDescriptor(
            name='img_path', full_name='Input.img_path', index=1,
            number=2, type=9, cpp_type=9, label=1,
            has_default_value=False, default_value=_b("").decode('utf-8'),
            message_type=None, enum_type=None, containing_type=None,
            is_extension=False, extension_scope=None,
            serialized_options=None, file=DESCRIPTOR),
    ],
    extensions=[
    ],
    nested_types=[],
    enum_types=[
    ],
    serialized_options=None,
    is_extendable=False,
    syntax='proto3',
    extension_ranges=[],
    oneofs=[
    ],
    serialized_start=21,
    serialized_end=61,
)


_OUTPUT = _descriptor.Descriptor(
    name='Output',
    full_name='Output',
    filename=None,
    file=DESCRIPTOR,
    containing_type=None,
    fields=[
        _descriptor.FieldDescriptor(
            name='delta_time', full_name='Output.delta_time', index=0,
            number=1, type=9, cpp_type=9, label=1,
            has_default_value=False, default_value=_b("").decode('utf-8'),
            message_type=None, enum_type=None, containing_type=None,
            is_extension=False, extension_scope=None,
            serialized_options=None, file=DESCRIPTOR),
        _descriptor.FieldDescriptor(
            name='top_5', full_name='Output.top_5', index=1,
            number=2, type=9, cpp_type=9, label=1,
            has_default_value=False, default_value=_b("").decode('utf-8'),
            message_type=None, enum_type=None, containing_type=None,
            is_extension=False, extension_scope=None,
            serialized_options=None, file=DESCRIPTOR),
    ],
    extensions=[
    ],
    nested_types=[],
    enum_types=[
    ],
    serialized_options=None,
    is_extendable=False,
    syntax='proto3',
    extension_ranges=[],
    oneofs=[
    ],
    serialized_start=63,
    serialized_end=106,
)

DESCRIPTOR.message_types_by_name['Input'] = _INPUT
DESCRIPTOR.message_types_by_name['Output'] = _OUTPUT
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Input = _reflection.GeneratedProtocolMessageType('Input', (_message.Message,), dict(
    DESCRIPTOR=_INPUT,
    __module__='image_recon_pb2'
    # @@protoc_insertion_point(class_scope:Input)
))
_sym_db.RegisterMessage(Input)

Output = _reflection.GeneratedProtocolMessageType('Output', (_message.Message,), dict(
    DESCRIPTOR=_OUTPUT,
    __module__='image_recon_pb2'
    # @@protoc_insertion_point(class_scope:Output)
))
_sym_db.RegisterMessage(Output)


_RECOGNIZER = _descriptor.ServiceDescriptor(
    name='Recognizer',
    full_name='Recognizer',
    file=DESCRIPTOR,
    index=0,
    serialized_options=None,
    serialized_start=108,
    serialized_end=177,
    methods=[
        _descriptor.MethodDescriptor(
            name='flowers',
            full_name='Recognizer.flowers',
            index=0,
            containing_service=None,
            input_type=_INPUT,
            output_type=_OUTPUT,
            serialized_options=None,
        ),
        _descriptor.MethodDescriptor(
            name='dogs',
            full_name='Recognizer.dogs',
            index=1,
            containing_service=None,
            input_type=_INPUT,
            output_type=_OUTPUT,
            serialized_options=None,
        ),
    ])
_sym_db.RegisterServiceDescriptor(_RECOGNIZER)

DESCRIPTOR.services_by_name['Recognizer'] = _RECOGNIZER

# @@protoc_insertion_point(module_scope)
